# Uncomment the next line to define a global platform for your project
# pilatform :ios, '9.0'

target 'AppFDJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppFDJ
  pod 'SwiftLint'
  pod 'Alamofire'

  target 'AppFDJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppFDJUITests' do
    # Pods for testing
  end

end
